global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "crypto-api"
    static_configs:
      - targets: ["api:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
